### ISSUE TITLE
Bug on the Garage screen opening the settings

### ISSUE THREAD

**Issue by DavBfr** [autodo-app/autodo#312]
Reproduction steps:
- Create 2 cars with the same name
- Open the settings

Actual result: Grey screen, no way to go back. And error log about non-unique Hero(). 

Expected result: Settings screen.

**Comment by baylessj** [comment]
Good catch. This is one obvious example of an error caused by having cars with overlapping names, but I'm guessing there will be others that would pop up as well. I believe the logic for updating estimated due dates assumes that car names are unique and there might be other places in the Bloc code as well.

We should probably make it a requirement in the Car add/edit form validator that the car names be unique so these issues don't occur.

**Comment by warriorCoder** [comment]
Why not use the car id instead of the name? That way cars can have the same name without conflict.
